name: Build and Create PR to Main

on:
  pull_request:
    types: closed
    branches: develop

jobs:
  build:
    if: github.event.pull_request.merged
    uses: ./.github/workflows/reusable-workflow-build.yml

  tests:
    name: Unit Tests + Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: make test

  create_pull_request:
    name: Create Pull Request to Main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/create-pull-request
        with:
          source_branch: 'develop'
          target_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
