name: Deploy

on:
  pull_request:
    types: closed
    branches: main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: eks-tech-challenge
  PROJECT_KEY: fiap-pos-tech-org_production-service-tech-challenge

jobs:
  sonar-analysis:
    if: |
      github.event.pull_request.merged &&
      github.ref == 'refs/heads/main'
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        run: make sonar-analysis SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Check SonarCloud coverage
        run: |
          COVERAGE=$(curl -sSf "https://sonarcloud.io/api/measures/component?component=$PROJECT_KEY&metricKeys=coverage" | jq -r '.component.measures[0].value')
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Cobertura de teste abaixo de 80%"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: sonar-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to EKS cluster
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Login to DockerHub
        run: docker login -u pedroprj -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t vwnunes/tech-challenge-61:latest .
          docker push vwnunes/tech-challenge-61

      # TODO: alterar a forma de criar as variáveis de ambiente abaixo pois o deployment da aplicação não está conseguindo enxergar ou pegar essas variáveis direto do ssm pela aplicação
      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment/cobranca-deployment.yaml
          kubectl apply -f deployment/cobranca-service.yaml
          kubectl apply -f deployment/alb-ingress.yaml
          kubectl get svc cobranca-service
          echo "DB_HOST=$(echo ${{ secrets.DB_HOST }})" >> $GITHUB_ENV
          echo "DB_USER=$(echo ${{ secrets.DB_USER }})" >> $GITHUB_ENV
          echo "DB_PASS=$(echo ${{ secrets.DB_PASS }})" >> $GITHUB_ENV